DELETE FROM Payments;
DELETE FROM ShipmentTracking;
DELETE FROM Shipments;
DELETE FROM Users;
DELETE FROM Addresses;
DELETE FROM PaymentMethods;
DELETE FROM ShipmentStatus;
DELETE FROM City;


DROP TABLE IF EXISTS Payments;
DROP TABLE IF EXISTS ShipmentTracking;
DROP TABLE IF EXISTS Shipments;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Addresses;
DROP TABLE IF EXISTS PaymentMethods;
DROP TABLE IF EXISTS ShipmentStatus;
DROP TABLE IF EXISTS City;
